package main

import (
	"flag"
	"fmt"
	"sort"
	"strings"
)

// completionShells are the shells `completion` can generate for.
var completionShells = []string{"bash", "zsh", "fish"}

// flagValues holds the flags whose accepted values are compiled into the
// binary. Completing them costs nothing -- no file is read and no process is
// forked -- which is why they are here and collection-derived values such as
// --genre are not. TestCompletionEnumValuesAreAccepted pins each value to what
// the parser actually takes.
var flagValues = map[string][]string{
	"draw":  {"fresh", "any", "stale"},
	"color": {"auto", "always", "never"},
}

// completionFlag is one flag as completion needs to see it.
type completionFlag struct {
	name   string
	isBool bool     // a bool flag takes no value, so nothing follows it
	values []string // compiled-in values, if any
}

// commandFlagSet builds the FlagSet a command parses with, without parsing
// anything. It is the single source completion enumerates and the parse
// functions register through, so a flag cannot be accepted by a command
// without also being offered for it.
func commandFlagSet(name string) *flag.FlagSet {
	// newFlagSet registers the global flags, so every command gets those
	// even when the switch below adds nothing.
	fs, _ := newFlagSet(name)
	switch name {
	case "pick", "list":
		addSelectionFlags(name, fs)
	case "history":
		addHistoryFlags(fs)
	case "favorite", "unfavorite":
		addFilterFlags(fs)
	case "sync":
		addSyncFlags(fs)
	}
	return fs
}

// commandFlags returns the flags a command accepts, sorted by name so the
// generated scripts are byte-stable between runs.
func commandFlags(name string) []completionFlag {
	var out []completionFlag
	commandFlagSet(name).VisitAll(func(f *flag.Flag) {
		out = append(out, completionFlag{
			name:   f.Name,
			isBool: isBoolFlag(f),
			values: flagValues[f.Name],
		})
	})
	sort.Slice(out, func(i, j int) bool { return out[i].name < out[j].name })
	return out
}

// isBoolFlag reports whether a flag is satisfied by its presence alone. The
// flag package marks these with an unexported interface that its own parser
// uses; asking the same question here keeps completion from suggesting a
// value where none is taken.
func isBoolFlag(f *flag.Flag) bool {
	bf, ok := f.Value.(interface{ IsBoolFlag() bool })
	return ok && bf.IsBoolFlag()
}

// parseCompletion validates completion's single argument, the shell name.
func parseCompletion(args []string) (string, error) {
	fs, _ := newFlagSet("completion")
	rest, err := parseInterspersed(fs, args)
	if err != nil {
		return "", fmt.Errorf("completion: %w", err)
	}
	if len(rest) == 0 {
		return "", fmt.Errorf("completion: requires a shell (%s)", strings.Join(completionShells, ", "))
	}
	if len(rest) > 1 {
		return "", fmt.Errorf("completion: too many arguments")
	}
	return rest[0], nil
}

// completionScript renders the completion script for one shell.
func completionScript(shell string) (string, error) {
	switch shell {
	case "bash":
		return bashCompletion(), nil
	case "zsh":
		return zshCompletion(), nil
	case "fish":
		return fishCompletion(), nil
	}
	return "", fmt.Errorf("unsupported shell %q (want %s)", shell, strings.Join(completionShells, ", "))
}

// shellQuote wraps a string for a single-quoted shell context. Command
// summaries are plain today, but a future one containing an apostrophe should
// not be able to break every user's completion.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// flagNames renders a command's flags as the space-separated --name list the
// bash and zsh scripts complete from.
func flagNames(name string) string {
	flags := commandFlags(name)
	names := make([]string, len(flags))
	for i, f := range flags {
		names[i] = "--" + f.name
	}
	return strings.Join(names, " ")
}

func commandNames() []string {
	names := make([]string, len(commands))
	for i, c := range commands {
		names[i] = c.name
	}
	return names
}

func bashCompletion() string {
	var sb strings.Builder
	sb.WriteString(`# bash completion for disc-fortune. Generated by ` + "`disc-fortune completion bash`" + `.
# Load with: eval "$(disc-fortune completion bash)"

_disc_fortune() {
    local cur prev cmd i
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # The first non-flag word is the subcommand; everything before it is a
    # global flag, and there may be none at all.
    cmd=""
    for ((i = 1; i < COMP_CWORD; i++)); do
        case "${COMP_WORDS[i]}" in
            -*) ;;
            *) cmd="${COMP_WORDS[i]}"; break ;;
        esac
    done

    # A flag that takes one of a fixed set of values.
    case "$prev" in
`)
	for _, name := range sortedKeys(flagValues) {
		fmt.Fprintf(&sb, "        --%s)\n            COMPREPLY=( $(compgen -W %s -- \"$cur\") )\n            return\n            ;;\n",
			name, shellQuote(strings.Join(flagValues[name], " ")))
	}
	sb.WriteString(`    esac

    if [[ "$cur" == -* ]]; then
        case "$cmd" in
`)
	for _, c := range commands {
		fmt.Fprintf(&sb, "            %s)\n                COMPREPLY=( $(compgen -W %s -- \"$cur\") )\n                ;;\n",
			c.name, shellQuote(flagNames(c.name)))
	}
	fmt.Fprintf(&sb, `            *)
                COMPREPLY=( $(compgen -W %s -- "$cur") )
                ;;
        esac
        return
    fi

    if [[ -z "$cmd" ]]; then
        COMPREPLY=( $(compgen -W %s -- "$cur") )
    fi
}

complete -F _disc_fortune disc-fortune
`, shellQuote(flagNames("")), shellQuote(strings.Join(commandNames(), " ")))

	return sb.String()
}

func zshCompletion() string {
	var sb strings.Builder
	sb.WriteString(`#compdef disc-fortune
# zsh completion for disc-fortune. Generated by ` + "`disc-fortune completion zsh`" + `.
# Load with: eval "$(disc-fortune completion zsh)"

_disc_fortune() {
    local -a subcommands
    subcommands=(
`)
	for _, c := range commands {
		// _describe takes name:description pairs, so a colon inside a
		// description would split it in the wrong place.
		desc := strings.ReplaceAll(c.summary, ":", `\:`)
		fmt.Fprintf(&sb, "        %s\n", shellQuote(c.name+":"+desc))
	}
	sb.WriteString(`    )

    local cmd="" i
    for (( i = 2; i < CURRENT; i++ )); do
        case ${words[i]} in
            -*) ;;
            *) cmd=${words[i]}; break ;;
        esac
    done

    case ${words[CURRENT-1]} in
`)
	for _, name := range sortedKeys(flagValues) {
		fmt.Fprintf(&sb, "        --%s)\n            _values %s %s\n            return\n            ;;\n",
			name, shellQuote(name), strings.Join(flagValues[name], " "))
	}
	sb.WriteString(`    esac

    if [[ ${words[CURRENT]} == -* ]]; then
        local -a flags
        case $cmd in
`)
	for _, c := range commands {
		fmt.Fprintf(&sb, "            %s) flags=(%s) ;;\n", c.name, flagNames(c.name))
	}
	fmt.Fprintf(&sb, `            *) flags=(%s) ;;
        esac
        compadd -- $flags
        return
    fi

    if [[ -z $cmd ]]; then
        _describe 'command' subcommands
    fi
}

compdef _disc_fortune disc-fortune
`, flagNames(""))

	return sb.String()
}

func fishCompletion() string {
	var sb strings.Builder
	sb.WriteString("# fish completion for disc-fortune. Generated by `disc-fortune completion fish`.\n")
	sb.WriteString("# Load with: disc-fortune completion fish | source\n\n")

	// disc-fortune takes no file arguments, so fish's default filename
	// completion is never right: without this, tab on a bare `disc-fortune `
	// lists the current directory instead of the subcommands.
	sb.WriteString("# No argument of any command is a path.\ncomplete -c disc-fortune -f\n\n")

	sb.WriteString("# Subcommands, offered only in the first position.\n")
	for _, c := range commands {
		fmt.Fprintf(&sb, "complete -c disc-fortune -n __fish_use_subcommand -a %s -d %s\n",
			shellQuote(c.name), shellQuote(c.summary))
	}

	sb.WriteString("\n# Flags, scoped to the commands that accept them.\n")
	for _, c := range commands {
		for _, f := range commandFlags(c.name) {
			line := fmt.Sprintf("complete -c disc-fortune -n %s -l %s",
				shellQuote("__fish_seen_subcommand_from "+c.name), f.name)
			switch {
			case len(f.values) > 0:
				// -x takes a value and offers only these.
				line += " -x -a " + shellQuote(strings.Join(f.values, " "))
			case !f.isBool:
				// Takes a value fish cannot guess: -r stops it
				// offering filenames as if the flag were a path.
				line += " -r"
			}
			sb.WriteString(line + "\n")
		}
	}

	sb.WriteString("\n# Global flags, accepted before a subcommand is typed too.\n")
	for _, f := range commandFlags("") {
		line := "complete -c disc-fortune -n __fish_use_subcommand -l " + f.name
		if len(f.values) > 0 {
			line += " -x -a " + shellQuote(strings.Join(f.values, " "))
		}
		sb.WriteString(line + "\n")
	}

	return sb.String()
}

// sortedKeys keeps generated output byte-stable: Go's map iteration order is
// deliberately random, and a script that differs between runs would show up as
// spurious diffs for anyone checking one in.
func sortedKeys(m map[string][]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func runCompletion(shell string) {
	script, err := completionScript(shell)
	if err != nil {
		fatal("Error: %v", err)
	}
	fmt.Print(script)
}
