package cli

import (
	"flag"
	"fmt"
	"io"
	"sort"
	"strings"
)

// Completion is the built-in completion command. Place it in
// Program.Commands where it should be listed. It needs no config: generating
// a script reads no data files, so it must keep working on a machine with no
// usable home directory.
func Completion[E any]() Spec[E] {
	return Spec[E]{
		Name:     "completion",
		Summary:  "Print a shell completion script",
		usageFor: completionUsage,
		New:      func() Command[E] { return &completionCmd[E]{} },
	}
}

// completionUsage is completion's usage block. It is built from the program
// name because the load instructions quote the command users type.
func completionUsage(program string) string {
	return strings.ReplaceAll(completionUsageTemplate, "{{name}}", program)
}

const completionUsageTemplate = `Usage: {{name}} completion SHELL

Prints a completion script for bash, zsh or fish on stdout. The script is
generated from the commands and flags this binary actually accepts, so it
cannot drift from them.

Load it for the current shell:

  bash    eval "$({{name}} completion bash)"
  zsh     eval "$({{name}} completion zsh)"
  fish    {{name}} completion fish | source

To make it permanent, add that line to your shell's startup file, or write the
script into the directory your shell reads completions from.

Command and flag names are completed, as are the fixed values of --draw and
--color. Values that would have to be read from your collection, such as those
of --genre and --label, are not: a completion should never depend on a file
that a sync may be rewriting.`

type completionCmd[E any] struct {
	p      *Program[E]
	stdout io.Writer
	g      *Globals
	shell  string
}

func (c *completionCmd[E]) bind(p *Program[E], stdout io.Writer) { c.p, c.stdout = p, stdout }

func (c *completionCmd[E]) Flags(_ *flag.FlagSet, g *Globals) { c.g = g }

// Parse validates completion's single argument, the shell name.
func (c *completionCmd[E]) Parse(rest []string) error {
	if len(rest) == 0 {
		return fmt.Errorf("completion: requires a shell (%s)", strings.Join(CompletionShells, ", "))
	}
	if len(rest) > 1 {
		return fmt.Errorf("completion: too many arguments")
	}
	// completion colorizes nothing, but it still accepts --color, so it must
	// still reject a bad value for it -- as every other command does.
	if _, err := c.g.Mode(); err != nil {
		return fmt.Errorf("completion: %v", err)
	}
	c.shell = rest[0]
	return nil
}

func (c *completionCmd[E]) Run(E) error {
	script, err := c.p.CompletionScript(c.shell)
	if err != nil {
		return fmt.Errorf("Error: %v", err)
	}
	fmt.Fprint(c.stdout, script)
	return nil
}

// script fills the program into a literal piece of a completion script:
// {{name}} is the binary's name, {{fn}} the shell function named after it,
// and {{default}} the command a leading flag means. Only literals pass
// through it -- never a command's summary or a flag's name -- so nothing a
// command says about itself can be rewritten.
func (p *Program[E]) script(s string) string {
	fn := "_" + strings.ReplaceAll(p.Name, "-", "_")
	return strings.NewReplacer("{{name}}", p.Name, "{{fn}}", fn, "{{default}}", p.Default).Replace(s)
}

// CompletionShells are the shells `completion` can generate for.
var CompletionShells = []string{"bash", "zsh", "fish"}

// CompletionScript renders the completion script for one shell.
func (p *Program[E]) CompletionScript(shell string) (string, error) {
	switch shell {
	case "bash":
		return p.bashCompletion(), nil
	case "zsh":
		return p.zshCompletion(), nil
	case "fish":
		return p.fishCompletion(), nil
	}
	return "", fmt.Errorf("unsupported shell %q (want %s)", shell, strings.Join(CompletionShells, ", "))
}

// shellQuote wraps a string for a single-quoted shell context. Command
// summaries are plain today, but a future one containing an apostrophe should
// not be able to break every user's completion.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// flagNames renders a command's flags as the space-separated --name list the
// bash and zsh scripts complete from.
func (p *Program[E]) flagNames(name string) string {
	flags := p.Flags(name)
	names := make([]string, len(flags))
	for i, f := range flags {
		names[i] = "--" + f.Name
	}
	return strings.Join(names, " ")
}

func (p *Program[E]) commandNames() []string {
	names := make([]string, len(p.Commands))
	for i, c := range p.Commands {
		names[i] = c.Name
	}
	return names
}

func (p *Program[E]) bashCompletion() string {
	var sb strings.Builder
	sb.WriteString(p.script(`# bash completion for {{name}}. Generated by `) + p.script("`{{name}} completion bash`") + p.script(`.
# Load with: eval "$({{name}} completion bash)"

{{fn}}() {
    local cur prev cmd i
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # The first non-flag word is the subcommand. There may be none: a leading
    # flag means the implicit {{default}} command, which is why the fallback below
    # completes {{default}}'s flags rather than only the global ones.
    cmd=""
    for ((i = 1; i < COMP_CWORD; i++)); do
        case "${COMP_WORDS[i]}" in
            -*) ;;
            *) cmd="${COMP_WORDS[i]}"; break ;;
        esac
    done

    # A flag that takes one of a fixed set of values.
    case "$prev" in
`))
	for _, name := range sortedKeys(p.FlagValues) {
		fmt.Fprintf(&sb, "        --%s)\n            COMPREPLY=( $(compgen -W %s -- \"$cur\") )\n            return\n            ;;\n",
			name, shellQuote(strings.Join(p.FlagValues[name], " ")))
	}
	fmt.Fprintf(&sb, `        %s)
            # Takes a value we cannot complete. Return empty rather than
            # falling through to the subcommand list.
            COMPREPLY=()
            return
            ;;
    esac

    if [[ "$cur" == -* ]]; then
        case "$cmd" in
`, strings.Join(p.freeValueFlags(p.Default), "|"))
	for _, c := range p.Commands {
		fmt.Fprintf(&sb, "            %s)\n                COMPREPLY=( $(compgen -W %s -- \"$cur\") )\n                ;;\n",
			c.Name, shellQuote(p.flagNames(c.Name)))
	}
	fmt.Fprintf(&sb, p.script(`            *)
                COMPREPLY=( $(compgen -W %s -- "$cur") )
                ;;
        esac
        return
    fi

    if [[ -z "$cmd" ]]; then
        COMPREPLY=( $(compgen -W %s -- "$cur") )
    fi
}

complete -F {{fn}} {{name}}
`), shellQuote(p.flagNames(p.Default)), shellQuote(strings.Join(p.commandNames(), " ")))

	return sb.String()
}

func (p *Program[E]) zshCompletion() string {
	var sb strings.Builder
	sb.WriteString(p.script(`#compdef {{name}}
# zsh completion for {{name}}. Generated by `) + p.script("`{{name}} completion zsh`") + p.script(`.
# Load with: eval "$({{name}} completion zsh)"

{{fn}}() {
    local -a subcommands
    subcommands=(
`))
	for _, c := range p.Commands {
		// _describe takes name:description pairs, so a colon inside a
		// description would split it in the wrong place.
		desc := strings.ReplaceAll(c.Summary, ":", `\:`)
		fmt.Fprintf(&sb, "        %s\n", shellQuote(c.Name+":"+desc))
	}
	sb.WriteString(`    )

    local cmd="" i
    for (( i = 2; i < CURRENT; i++ )); do
        case ${words[i]} in
            -*) ;;
            *) cmd=${words[i]}; break ;;
        esac
    done

    case ${words[CURRENT-1]} in
`)
	for _, name := range sortedKeys(p.FlagValues) {
		fmt.Fprintf(&sb, "        --%s)\n            _values %s %s\n            return\n            ;;\n",
			name, shellQuote(name), strings.Join(p.FlagValues[name], " "))
	}
	fmt.Fprintf(&sb, `        %s)
            # Takes a value we cannot complete.
            return
            ;;
    esac

    if [[ ${words[CURRENT]} == -* ]]; then
        local -a flags
        case $cmd in
`, strings.Join(p.freeValueFlags(p.Default), "|"))
	for _, c := range p.Commands {
		fmt.Fprintf(&sb, "            %s) flags=(%s) ;;\n", c.Name, p.flagNames(c.Name))
	}
	fmt.Fprintf(&sb, p.script(`            *) flags=(%s) ;;
        esac
        compadd -- $flags
        return
    fi

    if [[ -z $cmd ]]; then
        _describe 'command' subcommands
    fi
}

# Sourced (eval) this registers the function; autoloaded from fpath, zsh calls
# the file *as* the completion function, so it must run rather than re-register.
if [ "$funcstack[1]" = "{{fn}}" ]; then
    {{fn}} "$@"
else
    compdef {{fn}} {{name}}
fi
`), p.flagNames(p.Default))

	return sb.String()
}

// freeValueFlags are the flags that take a value completion cannot supply --
// the collection-derived ones. bash and zsh need them named explicitly: their
// scripts fall through to the subcommand list otherwise, offering command
// names as the value of --genre. fish gets this for free from -x.
func (p *Program[E]) freeValueFlags(command string) []string {
	var out []string
	for _, f := range p.Flags(command) {
		if !f.IsBool && len(f.Values) == 0 {
			out = append(out, "--"+f.Name)
		}
	}
	return out
}

// fishValueSpec renders what fish should offer after a flag.
//
// -x is load-bearing: -r means only "this option takes an argument" and leaves
// fish's default filename completion in place, so `--genre <TAB>` offered the
// working directory. The file-scoped `complete -c <name> -f` does not
// reach an option's argument. -x is -r plus "offer nothing else".
func fishValueSpec(f FlagInfo) string {
	switch {
	case len(f.Values) > 0:
		return " -x -a " + shellQuote(strings.Join(f.Values, " "))
	case !f.IsBool:
		return " -x"
	}
	return ""
}

func (p *Program[E]) fishCompletion() string {
	var sb strings.Builder
	sb.WriteString(p.script("# fish completion for {{name}}. Generated by `{{name}} completion fish`.\n"))
	sb.WriteString(p.script("# Load with: {{name}} completion fish | source\n\n"))

	// No command takes a file argument, so fish's default filename
	// completion is never right: without this, tab on a bare `<name> `
	// lists the current directory instead of the subcommands.
	sb.WriteString(p.script("# No argument of any command is a path.\ncomplete -c {{name}} -f\n\n"))

	sb.WriteString("# Subcommands, offered only in the first position.\n")
	for _, c := range p.Commands {
		fmt.Fprintf(&sb, p.script("complete -c {{name}} -n __fish_use_subcommand -a %s -d %s\n"),
			shellQuote(c.Name), shellQuote(c.Summary))
	}

	sb.WriteString("\n# Flags, scoped to the commands that accept them.\n")
	for _, c := range p.Commands {
		for _, f := range p.Flags(c.Name) {
			fmt.Fprintf(&sb, p.script("complete -c {{name}} -n %s -l %s%s\n"),
				shellQuote("__fish_seen_subcommand_from "+c.Name), f.Name, fishValueSpec(f))
		}
	}

	// A bare `<name> --genre jazz` runs the default command: Resolve treats a
	// leading flag that way. So the no-subcommand position takes its
	// flags, not merely the global ones.
	sb.WriteString(p.script("\n# Before a subcommand is typed, a flag means the implicit `{{default}}`.\n"))
	for _, f := range p.Flags(p.Default) {
		fmt.Fprintf(&sb, p.script("complete -c {{name}} -n __fish_use_subcommand -l %s%s\n"),
			f.Name, fishValueSpec(f))
	}

	return sb.String()
}

// sortedKeys keeps generated output byte-stable: Go's map iteration order is
// deliberately random, and a script that differs between runs would show up as
// spurious diffs for anyone checking one in.
func sortedKeys(m map[string][]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
